#!/bin/sh
#
# @name Swan K1 Quad Tailsitter VTOL (DEP Tailsitter VTOL Test)
#
# @type DEP VTOL Tailsitter
# @class VTOL
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default MAV_TYPE 20

param set-default SYS_CTRL_ALLOC 1

param set-default CA_AIRFRAME 4
param set-default CA_ROTOR_COUNT 8
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.23
param set-default CA_ROTOR0_PZ 0.23
param set-default CA_ROTOR0_CT 6.5
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.23
param set-default CA_ROTOR1_PZ 0.23
param set-default CA_ROTOR1_CT 6.5
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.23
param set-default CA_ROTOR2_PZ 0.23
param set-default CA_ROTOR2_CT 6.5
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.23
param set-default CA_ROTOR3_PZ 0.23
param set-default CA_ROTOR3_CT 6.5
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR4_PX 0.15
param set-default CA_ROTOR4_PY 0.23
param set-default CA_ROTOR4_PZ 0.23
param set-default CA_ROTOR4_CT 6.5
param set-default CA_ROTOR4_KM -0.05
param set-default CA_ROTOR5_PX 0.15
param set-default CA_ROTOR5_PY 0.23
param set-default CA_ROTOR5_PZ 0.23
param set-default CA_ROTOR5_CT 6.5
param set-default CA_ROTOR5_KM -0.05
param set-default CA_ROTOR6_PX 0.15
param set-default CA_ROTOR6_PY 0.23
param set-default CA_ROTOR6_PZ 0.23
param set-default CA_ROTOR6_CT 6.5
param set-default CA_ROTOR6_KM -0.05
param set-default CA_ROTOR7_PX 0.15
param set-default CA_ROTOR7_PY 0.23
param set-default CA_ROTOR7_PZ 0.23
param set-default CA_ROTOR7_CT 6.5
param set-default CA_ROTOR7_KM -0.05


#output allocation
#min pwm (1100)
#controller tuning

param set-default VT_MC_CS_LOCK 0

param set-default VT_TYPE 0
# Add Airspeed Sensor Parameter here
#param set-default SENS_EN_MS4525DO 1
